export const AGNATIVE_DEFAULTS = {
  enabled: 'on',
  glare: 'on',
  topnavItems: ['main', 'movie', 'tv', 'cartoon'],
  logoLang: 'auto',
  fontSize: 'md',
  uiLang: 'auto',
  backdrop: 'on',
  badge: 'on',
  rating: 'off',
  ratingStyle: 'color',
  categorySize: 'md',
  cardSize: 'md',
  logoSize: 'md',
  cacheSize: '100',
  clockSeconds: 'off',
  controlPanel: 'off',
  perfMode: 'auto',
  cardImageMode: 'backdrop'
};
