export const AGNATIVE_KEYS = {
  STYLE_ID: 'appletv-agnative-topnav-style',
  BODY_CLASS: 'appletv-agnative-topnav',
  CLOCK_ID: 'agnative-topnav-clock',
  TMDB_KEY: '4ef0d7355d9ffb5151e987764708ce96',
  ENABLE_KEY: 'appletv_agnative_topnav_enabled',
  GLARE_KEY: 'appletv_agnative_topnav_glare_enabled',
  TOPNAV_ITEMS_KEY: 'appletv_agnative_topnav_items',
  LOGO_LANG_KEY: 'appletv_agnative_logo_lang',
  FONT_SIZE_KEY: 'appletv_agnative_font_size',
  UI_LANG_KEY: 'appletv_agnative_ui_lang',
  BACKDROP_KEY: 'appletv_agnative_backdrop',
  BADGE_KEY: 'appletv_agnative_badge',
  RATING_KEY: 'appletv_agnative_rating',
  RATING_STYLE_KEY: 'appletv_agnative_rating_style',
  CATEGORY_SIZE_KEY: 'appletv_agnative_category_size',
  CLOCK_SECONDS_KEY: 'appletv_agnative_clock_seconds',
  CONTROL_PANEL_KEY: 'appletv_agnative_control_panel',
  SETTINGS_COMPONENT: 'agnative',
  TOPNAV_SETTINGS_COMPONENT: 'agnative_topnav',
  GLARE_CLASS: 'appletv-agnative-topnav-glare',
  FONT_SIZE_ATTR: 'data-agnative-font',
  BACKDROP_ATTR: 'data-agnative-backdrop',
  BADGE_ATTR: 'data-agnative-badge',
  RATING_ATTR: 'data-agnative-rating',
  RATING_STYLE_ATTR: 'data-agnative-rating-style',
  CATEGORY_SIZE_ATTR: 'data-agnative-category'
};
